exports.Normalizacion = function(Plb){
    Plb=Plb.normalize('NFD').toLowerCase().replace(/[\u0300-\u036f]/g, '').replace(/[.]/g,'').replace('b','v').replace('z','s')
    let L0=[0];
    let L1=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','t','s','u','v','w','x','y','z'];
    let L2=['le','en','el','al','si','no','mi','de','la','su','es','un','ha','ya','lo','se','mx','me','tu']
    let L3=['con','los','del','soy','que','sea','fue','gob','una','las','pdf','por','vez','son','sin','han','aqv','ser','dar','web','ese','etc','mas','asi','mis','ver','jsf','dia','rol','sus','dan','uno','iii','dos','ano','esa','cvu','sni']
    let L4=['dias','algo','como','cual','para','clic','este','tipo','pais','link','caso','spam','siga','cabo','azul','esta','area','issn','toda','ello','debe','esto','alta','otro','diez','pero','sera','cada','siat','ante','haya','lado','solo','miic','bien','debo','todo','anos','obra','sean','hora','alto','sola','usan','base','dado','beca','hola','menu','curp']
    let L5=['saber','puedo','temas','estoy','pasos','clave','unica','tenga','linea','sobre','boton','nunca','tenia','nuevo','robot','desde','https','nueva','carta','tinta','copia','podra','desea','donde','autor','puede','estan','todas','estos','texto','campo','pegar','tiene','datos','favor','llene','razon','misma','poder','notas','algun','medio','ahora','nivel','dando','dicha','menor','tener','antes','movil','abrir','llave','hacer','parte','icono','forma','lista','pueda','mismo','usted','envio','menos','estar','deben','tengo','citas','anexe','elegi','tesis','grado','deseo','legal','casos','haber','hayas','todos','fondo','color','verde','esten','bases','fecha','libro','etapa','hasta','siete','seran','resto','desee','hayan','llega','envia','tecla','error','becas','firma']
    let L6=['buenos','ayudar','quiero','contar','activo','debera','pagina','nuevos','cuenta','tenido','cuento','marcar','campos','marque','nombre','enviar','centro','llevar','cambio','simple','motivo','actual','anexar','cedula','acepta','libros','dentro','seguir','copiar','numero','llenar','google','social','aplica','partir','primer','mexico','alumno','tratar','cumple','cuatro','cuando','oficio','opcion','ningun','editar','genere','verla,','tengan','estado','adeudo','buscar','obtuvo','manera','cuales','inclui','evalue','cierre','tamano','maximo','pueden','cubrir','avalar','alguna','limite','querer','sujeto','podran','global','fisica','cambia','traves','perish','origen','dichos','poseer','minimo','senala','grados','volver','codigo','accion','acceso','s.n.i.','firmar','correo','scopus','inicio']
    let L7=['cambiar','obtener','ingrese','seccion','sistema','proceso','casilla','aceptar','validar','indicar','enviara','bandeja','entrada','carpeta','palabra','capturo','momento','activar','soporte','tecnico','capture','redacte','formato','firmada','oficial','legible','digital','muestre','permite','guardar','aparece','agregar','empresa','permita','existan','funcion','guiones','deberse','autores','primero','acentos','ejemplo','pediran','adecuar','consejo','ciencia','centros','federal','colocar','muestra','mensaje','estatus','embargo','algunas','iniciar','digitos','intento','posible','privada','ninguna','reporte','tramite','recibio','derecha','deseado','ubicado','columna','captura','postula','termino','realice','cumplan','vigente','generar','periodo','lectivo','informe','despues','becario','enviado','editado','ponerse','mozilla','derecho','alumnos','correos','numeros','incluir','patente','revisar','paginas','archivo','trabajo','scholar','science','tambien','llamado','publish','enviada','cuenten','adeudos','espacio','evaluar','estaran','marcada','medicos','cumplir','tarjeta','deberan','senalar','acuerdo','ultimas','esperar','laboral','firefox','copiado','pegarlo','utiliza','firmado','obtengo','usuario','conacyt','thomson','ingreso','inicial']
    let L8=['presiona','realizar','ingresar','superior','apartado','anterior','presione','recuerda','obtendra','nacional','mostrara','pantalla','correcto','correcta','buscarlo','deseados','completo','atendera','contener','telefono','contacto','oficinas','mediante','utilizar','buscador','articulo','catalogo','marcados','capturar','guardado','habilite','empresas','registre','ejemplos','etcetera','postular','requiere','corregir','convenio','intentar','confirme','activada','programa','acciones','posgrado','cambiara','borrador','reciente','colocado','conocera','consulta','necesita','regresar','devolver','requiera','adecuada','vigencia','requiero','comienza','concluye','activara','rechazar','contario','explorer','recuadro','becarios','imprimir','indicado','enviados','producto','archivos','adjuntar','coincide','adecuado','paquetes','subiendo','amarillo','habiendo','vertical','legibles','busqueda','trabajos','software','enviarla','estricto','dictamen','aparecen','muestran','patentes','aquellos','senalada','acredite','expedida','obtenido','estimulo','personas','bancaria','tramites','proyecto','internet','inferio','usuarios','registro','recuerdo','sistemas','retornar']
    let L9=['necesario','siguiente','poblacion','principal','servicios','continuar','senalados','contrario','confirmar','registrar','indicando','pasaporte','enviarlas','secciones','colocando','articulos','asterisco','capturado','fundacion','generales','validarla','documento','programas','escaneada','aspirante','encuentra','criterios','academico','bloqueado','consultar','capturada','presionar','completar','requisito','completos','recuperar','encuentre','contactar','pendiente','concluido','posterior','desempeno','operadora','encontrar','direccion','capitulos','localizar','percatado','solicitar','doctorado','concursar','obtencion','ocasiones','situacion','publicada','verificar','contenida','recibiran','adjuntado','productos','presenten','facilitar','sugerimos','ordenadas','prestigio','sometidas','concluida','megabytes','destinado','evaluados','destacada','presentar','instituto','migracion','requerido','favorable','economico','reingreso','izquierdo','mostraran','recepcion','habilitan','solicitud']
    let L10=['siguientes','preguntara','seleccione','selecciono','validacion','capturelos','nacimiento','recomienda','fotografia','documentos','diferentes','capturando','correccion','caracteres','especiales','formulario','disponible','importante','nacionales','extranjera','especifica','mencionado','adjuntando','membretado','informamos','tecnologia','facultades','institutos','pertenecen','requeridas','actualizar','requeridos','formalizar','liberacion','establezca','conformada','encontrado','realizados','anteriores','relevantes','necesarias','incompleta','visualizar','postularlo','aspirantes','capturados','telefonico','pendientes','extranjero','peoplesoft','obtuvieron','ingresando','automatiza','registrada','produccion','finalizado','probatorio','reapertura','desarrollo','participar','residencia','resultados','cientifica','evaluacion','existentes','comisiones','consideren','adjuntarse','asegurarse','completado','plataforma','probatoria','encuentren','presentado','explicando','publicadas','unicamente','concedidas','constancia','destacados','claramente','reglamento','solicitado','publicados','realizando','bloqueados','contrasena','registrado','curriculum']
    let L11=['informacion','identifique','presionando','seleccionar','identificar','indicandole','presentarla','publicacion','institucion','corresponde','importantes','instruccion','registrando','tecnologico','coordinador','postulacion','contactarme','registrarse','solicitante','solicitudes','solicitados','completadas','comuniquese','encontrarse','terminacion','navegadores','comunicarse','contactanos','telefonicos','digitalizar','adscripcion','tecnologica','debidamente','probatorios','orientacion','establecida','editoriales','desarrollos','presentados','desplegaran','disposicion','adicionales','especificos','comprobante','establecido','consecutiva','designacion','cancelacion','restablecer','corresponda','electronica','electronico']
    let L12=['relacionados','nacionalidad','continuacion','directamente','obligatorios','incorporando','verificacion','tecnologicos','convocatoria','complementar','coordinacion','correcciones','modificacion','recomendamos','electronicos','contactarlos','conocimiento','investigador','equivalentes','considerados','otorgamiento','preferencial','equivalencia','presentacion','nombramiento','notificacion','alfanumerica']
    let L13=['inhabilitados','universidades','instituciones','anteriormente','convocatorias','departamentos','inconveniente','postulaciones','instrucciones','correctamente','procedimiento','formalizacion','liberacion/no','documentacion','investigacion','participacion','actualizacion','beneficiarios']
    let L14=['autografamente','identificacion','modificaciones','investigadores','dictaminadoras','sobresalientes','posteriormente']
    let L15=['caracteristicas','correspondiente','internacionales']
  
    let LT=[L0,L1,L2,L3,L4,L5,L6,L7,L8,L9,L10,L11,L12,L13,L14,L15];

    Plb=String(Plb).split(' ')
    console.log(Plb)
    let PhrF=''
    for(let i in Plb){
      let WorldF=''
      let Mx=0;
      let V=[0,0,0];
      let lPlb=Plb[i].length
      for(let D=-Math.round(lPlb/4);D<=Math.round(lPlb/4);D++){
        if(D<0){V=[1,0,lPlb+D,]}
        else{V=[0,1,lPlb]}
        for(let d=0;d<=Math.abs(D);d++){
          for(let e in LT[lPlb+D]){
            let SL=0;
            let homofonas=String(LT[lPlb+D][e]).replace('b','v').replace('z','s')
            for(let L=0;L<V[2];L++){
              if(Plb[i][L+d*V[0]]==homofonas[L+d*V[1]]){
                SL++}}
            if(SL/(lPlb+D)>=0.667 &&  SL/(lPlb+D)>=Mx){
              Mx=SL/(lPlb+D)*Math.pow(Math.E,-(Math.pow(D,2)/(2*Math.pow(lPlb/4,2))  ))//Math.pow(Math.E,-(pow(D,2))/(2*pow(lPlb/4,2)))
              WorldF=LT[lPlb+D][e]}}}}
      PhrF=PhrF+' '+WorldF}
    return PhrF;
}

