DROP TABLE customer IF EXISTS;
CREATE TABLE customer ( CUST_ID int GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
                        NAME varchar(100) NOT NULL,   
                        AGE int NOT NULL,   PRIMARY KEY (CUST_ID) ); 
